### obtener todos los clientes
GET http://localhost:3000/api/clients


### obtener un cliente
GET http://localhost:3000/api/clients/1



### crear un nuevo cliente
POST http://localhost:3000/api/clients
Content-Type: application/json

{
  "dni": "45684304",
  "firstname": "Franco",
  "lastname": "Mascheroni",
  "address": "Mitre 1430",
  "phone": "34163493854",
  "email": "masche494@gmail.com",
  "registrationDate": "30/08/2003"
}




### modificar un cliente (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/clients/1
Content-Type: application/json

{
  "dni": "44523096",
  "firstname": "Facundo Nahuel",
  "lastname": "Munne",
  "address": "3 de febrero 377",
  "phone": "3416470473",
  "email": "fnmunne@frro.ar",
  "registrationDate": "08/12/2002"
}

### modificar un cliente (PATCH - recurso parcial)
PATCH http://localhost:3000/api/clients/4
Content-Type: application/json

{
  "firstname": "Sebastian Gonzalez",
  "address": "Peru 1500",
  "email": "sebigonzi@gmail.com"  
}

### borrar un cliente
DELETE http://localhost:3000/api/clients/2